version: 2.1

commands:
  print_pipeline_id:
    parameters:
      branch:
        type: string
    steps:
      - run: echo <<  parameters.git.branch >>

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          branch: << pipeline.branch >>

workflows:
  my_workflow:
    jobs:
      - my_job
