---
- name: "update apt packages."
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove Dependencies no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install dependencies"
  # Elevate priviledge to sudo
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  # Elevate priviledge to sudo
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create web directory"
  file:
    path: ~/web
    state: directory

- name: "Copy Index Page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Execute node"
  shell: |
    pm2 start ~/web/index.js -f